### ISSUE TITLE
Adding pagination

### ISSUE THREAD

**Issue by WesselH** [mediamonks/henk#1]
Too many iframes being loaded at once will cause lagg/loading issues. Pagination would probably solve this. 

Example: https://eu.richmedia-previews.dev.monkapps.com/cae82f23-72af-4a10-85ce-4b9f6042305f/index.html

**Comment by mientjan** [comment]
not relavent to henk

**Comment by WesselBoomerang** [comment]
Thank you for the quick reply @mientjan

Keep up the good work! <3
