### ISSUE TITLE
Add better description

### ISSUE THREAD

**Issue by psimk** [mediamonks/henk#7]
As a newcomer to the project, the `README` doesn't explain why and how I would use this tool.
I don't want to install an NPM package and then spend the next 10 or so minutes figuring out how to use it and if its actual what I need. IMO, all of this should be documented and presented front first.

As a side note, perhaps adding an example using `npx` would also be useful, for those one time users.

**Comment by mientjan** [comment]
There is not a lot of documentation needed for this project. Its a cli tool and only a cli tool.

"Uploading files to a location. through the command line." I dont know how to describe it any other way.

Installation
```yarn global add @mediamonks/henk```
```npm i -G @mediamonks/henk```

Lets start
```henk```

the entire process is self explanatory after calling the cli henk. thats the entire intent of the tool.
